name: Java CI with Docker

on:
  push:
  pull_request:

env:
  DOCKER_IMAGE_NAME: ktenman/automaks
  DOCKER_IMAGE_TAG: ${{ github.sha }}

jobs:
  test:
    runs-on: ubuntu-latest
    container: maven:3.9-eclipse-temurin-21-alpine
    steps:
      - uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 1
      - uses: actions/cache@v4.0.2
        with:
          path: |
            ~/.m2/repository
            !~/.m2/repository/ee/tenman
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2-
      - run: mvn -T 1C --quiet -Dparallel=methods -DthreadCount=2 --batch-mode test

  build_and_push:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [ linux/amd64, linux/arm64/v8 ]
    steps:
      - uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3.3.0
      - name: Log in to Docker Hub
        uses: docker/login-action@v3.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_IMAGE_NAME }}:latest
          cache-from: type=registry,ref=${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }}
          cache-to: type=inline
          platforms: linux/amd64, linux/arm64/v8
      - name: Trigger Deploy in Elektrihind
        if: matrix.platform == 'linux/amd64' && success()
        run: |
          response=$(curl -X POST \
            -H "Authorization: token ${{ secrets.ELEKTRIHIND_REPOSITORY_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/ktenman/elektrihind/dispatches \
            -d '{"event_type": "trigger-deploy"}' \
            -s -w "Response: %{http_code}")
          echo "Trigger response: $response"

  auto-merge-dependabot:
    name: 🤖 Auto merge dependabot PR
    needs: [ test ]
    if: github.actor == 'dependabot[bot]' && github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: 🤖 Merge PR from dependabot
        uses: fastify/github-action-merge-dependabot@v3.10.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          target: minor
          merge-method: rebase
